apiVersion: v2
name       : App-HelmChart
description: My Helm chart for Kubernetes
type       : application
version    : 0.1.0   # This is the Helm Chart version
appVersion : "0.1.0" # This is the version of the application being deployed

maintainers:
  - name : Mikhail Gorchanyuk
    email: gorchanyk@gmail.com

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.5.17

  - name: kafka
    repository: https://charts.bitnami.com/bitnami
    version: 29.3.8

  - name:  producer
    repository: file://../chart-producer
    version: 0.1.0

  - name: consumer
    repository: file://../chart-consumer
    version: 0.1.0

#  - name: ingress-nginx
#    repository: https://kubernetes.github.io/ingress-nginx
#    version: 4.10.2
#    alias: ingressconsumer

  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.10.2
    alias: ingressproducer
