# Default Values for my Helm Chart

consumer:
  datasource:
    host: postgres
  kafka:
    host: kafka

producer:
  kafka:
    host: kafka

postgresql:
  fullnameOverride: postgres
  auth:
    username: postgres
    password: postgres
    database: t1

kafka:
  fullnameOverride: kafka
  broker:
    minId: 1
  listeners:
    client:
      protocol: PLAINTEXT
  metrics:
    jmx:
      enabled: true


ingressconsumer:
  controller:
    ingressClass: consumer
    ingressClassResource:
      controllerValue: k8s.io/ingressconsumer
      name: consumer
    service:
      ports:
        http: 8091

ingressproducer:
  controller:
    ingressClass: producer
    ingressClassResource:
      controllerValue: k8s.io/ingressproducer
      name: producer
    service:
      ports:
        http: 8090

ingressprometheus:
  controller:
    ingressClass: prometheus
    ingressClassResource:
      controllerValue: k8s.io/ingressprometheus
      name: prometheus
    service:
      ports:
        http: 9090

prometheus:
  server:
    fullnameOverride: prometheus



