# Default Values for my Helm Chart

consumer:
  datasource:
    host: postgres
  kafka:
    host: kafka

producer:
  kafka:
    host: kafka

postgresql:
  fullnameOverride: postgres
  auth:
    username: postgres
    password: postgres
    database: t1

kafka:
  fullnameOverride: kafka
  broker:
    minId: 1
  listeners:
    client:
      protocol: PLAINTEXT

ingressconsumer:
  controller:
    ingressClassResource:
      name: consumer
    service:
      ports:
        http: 8091

ingressproducer:
  controller:
    ingressClassResource:
      name: producer
    service:
      ports:
        http: 8090


