# Default Values for my Helm Chart

consumer:
  datasource:
    host: postgres
  kafka:
    host: kafka
  jaeger:
    host: host
    port: 4318

producer:
  kafka:
    host: kafka
  jaeger:
    host: host
    port: 4318

postgresql:
  fullnameOverride: postgres
  auth:
    username: postgres
    password: postgres
    database: t1

kafka:
  fullnameOverride: kafka
  broker:
    minId: 1
  listeners:
    client:
      protocol: PLAINTEXT
  metrics:
    jmx:
      enabled: true


ingressconsumer:
  controller:
    ingressClass: consumer
    ingressClassResource:
      controllerValue: k8s.io/ingressconsumer
      name: consumer
    service:
      ports:
        http: 8091

ingressproducer:
  controller:
    ingressClass: producer
    ingressClassResource:
      controllerValue: k8s.io/ingressproducer
      name: producer
    service:
      ports:
        http: 8090

ingressprometheus:
  controller:
    ingressClass: prometheus
    ingressClassResource:
      controllerValue: k8s.io/ingressprometheus
      name: prometheus
    service:
      ports:
        http: 9090

ingressjaeger:
  controller:
    ingressClass: jaeger
    ingressClassResource:
      controllerValue: k8s.io/ingressjaeger
      name: jaeger
    service:
      ports:
        http: 16686

prometheus:
  server:
    fullnameOverride: prometheus

jaeger:
  provisionDataStore:
    cassandra: false
  allInOne:
    enabled: true
  storage:
    type: memory
  agent:
    enabled: false
  collector:
    enabled: false
  query:
    enabled: false



