apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingressconsumer.controller.ingressClassResource.name}}
spec:
  ingressClassName: {{ .Values.ingressconsumer.controller.ingressClassResource.name}}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.consumer.name}}
                port:
                  number: {{ .Values.consumer.port}}