apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingressproducer.controller.ingressClassResource.name}}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressproducer.controller.ingressClassResource.name}}
spec:
  ingressClassName: {{ .Values.ingressproducer.controller.ingressClassResource.name}}
  rules:
    - host: producer
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.producer.name}}
                port:
                  number: {{ .Values.producer.port}}
    - host: consumer
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.consumer.name}}
                port:
                  number: {{ .Values.consumer.port}}