# Default Values for my Helm Chart

replicaCount: 1
name: consumer
image: bezbasheniy/gorchanyuk.consumer:latest
port: 8091
targetPort: 8091
datasource:
  host: host
  username: postgres
  password: postgres
kafka:
  host: kafka
  port: 9092



