apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.name}}
    spec:
      containers:
        - name: {{ .Values.name}}
          image: {{ .Values.image}}
          ports:
            - containerPort: {{ .Values.port}}
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Values.datasource.host}}:5432/t1
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.datasource.username}}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.datasource.password}}
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              value: {{ .Values.kafka.bootstrap_server}}
          imagePullPolicy: Always